<?php
/**
 * Order
 *
 * PHP version 5
 *
 * @category Class
 * @package  Carooline
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * sale REST services
 *
 * Get or Update Sales
 *
 * OpenAPI spec version: 0.1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.13
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Carooline\Model;

use \ArrayAccess;
use \Carooline\ObjectSerializer;

/**
 * Order Class Doc Comment
 *
 * @category Class
 * @package  Carooline
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Order implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Order';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'print_href' => 'string',
'consignee_id' => 'int',
'amount_untaxed' => 'float',
'name' => 'string',
'partner_shipping_id' => 'int',
'order_line' => '\Carooline\Model\OrderLine[]',
'mobile' => 'string',
'amount_tax' => 'float',
'invoice_ids' => '\Carooline\Model\OrderInvoiceIds[]',
'state' => 'string',
'carrier' => '\Carooline\Model\OrderCarrier',
'payment_transaction' => '\Carooline\Model\OrderPaymentTransaction',
'client_order_ref' => 'string',
'partner_invoice_id' => 'int',
'partner' => '\Carooline\Model\Partner',
'date_order' => 'string',
'id' => 'int',
'amount_total' => 'float'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'print_href' => null,
'consignee_id' => null,
'amount_untaxed' => 'float',
'name' => null,
'partner_shipping_id' => null,
'order_line' => null,
'mobile' => null,
'amount_tax' => 'float',
'invoice_ids' => null,
'state' => null,
'carrier' => null,
'payment_transaction' => null,
'client_order_ref' => null,
'partner_invoice_id' => null,
'partner' => null,
'date_order' => null,
'id' => null,
'amount_total' => 'float'    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'print_href' => 'print_href',
'consignee_id' => 'consignee_id',
'amount_untaxed' => 'amount_untaxed',
'name' => 'name',
'partner_shipping_id' => 'partner_shipping_id',
'order_line' => 'order_line',
'mobile' => 'mobile',
'amount_tax' => 'amount_tax',
'invoice_ids' => 'invoice_ids',
'state' => 'state',
'carrier' => 'carrier',
'payment_transaction' => 'payment_transaction',
'client_order_ref' => 'client_order_ref',
'partner_invoice_id' => 'partner_invoice_id',
'partner' => 'partner',
'date_order' => 'date_order',
'id' => 'id',
'amount_total' => 'amount_total'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'print_href' => 'setPrintHref',
'consignee_id' => 'setConsigneeId',
'amount_untaxed' => 'setAmountUntaxed',
'name' => 'setName',
'partner_shipping_id' => 'setPartnerShippingId',
'order_line' => 'setOrderLine',
'mobile' => 'setMobile',
'amount_tax' => 'setAmountTax',
'invoice_ids' => 'setInvoiceIds',
'state' => 'setState',
'carrier' => 'setCarrier',
'payment_transaction' => 'setPaymentTransaction',
'client_order_ref' => 'setClientOrderRef',
'partner_invoice_id' => 'setPartnerInvoiceId',
'partner' => 'setPartner',
'date_order' => 'setDateOrder',
'id' => 'setId',
'amount_total' => 'setAmountTotal'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'print_href' => 'getPrintHref',
'consignee_id' => 'getConsigneeId',
'amount_untaxed' => 'getAmountUntaxed',
'name' => 'getName',
'partner_shipping_id' => 'getPartnerShippingId',
'order_line' => 'getOrderLine',
'mobile' => 'getMobile',
'amount_tax' => 'getAmountTax',
'invoice_ids' => 'getInvoiceIds',
'state' => 'getState',
'carrier' => 'getCarrier',
'payment_transaction' => 'getPaymentTransaction',
'client_order_ref' => 'getClientOrderRef',
'partner_invoice_id' => 'getPartnerInvoiceId',
'partner' => 'getPartner',
'date_order' => 'getDateOrder',
'id' => 'getId',
'amount_total' => 'getAmountTotal'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['print_href'] = isset($data['print_href']) ? $data['print_href'] : null;
        $this->container['consignee_id'] = isset($data['consignee_id']) ? $data['consignee_id'] : null;
        $this->container['amount_untaxed'] = isset($data['amount_untaxed']) ? $data['amount_untaxed'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['partner_shipping_id'] = isset($data['partner_shipping_id']) ? $data['partner_shipping_id'] : null;
        $this->container['order_line'] = isset($data['order_line']) ? $data['order_line'] : null;
        $this->container['mobile'] = isset($data['mobile']) ? $data['mobile'] : null;
        $this->container['amount_tax'] = isset($data['amount_tax']) ? $data['amount_tax'] : null;
        $this->container['invoice_ids'] = isset($data['invoice_ids']) ? $data['invoice_ids'] : null;
        $this->container['state'] = isset($data['state']) ? $data['state'] : null;
        $this->container['carrier'] = isset($data['carrier']) ? $data['carrier'] : null;
        $this->container['payment_transaction'] = isset($data['payment_transaction']) ? $data['payment_transaction'] : null;
        $this->container['client_order_ref'] = isset($data['client_order_ref']) ? $data['client_order_ref'] : null;
        $this->container['partner_invoice_id'] = isset($data['partner_invoice_id']) ? $data['partner_invoice_id'] : null;
        $this->container['partner'] = isset($data['partner']) ? $data['partner'] : null;
        $this->container['date_order'] = isset($data['date_order']) ? $data['date_order'] : null;
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['amount_total'] = isset($data['amount_total']) ? $data['amount_total'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['partner'] === null) {
            $invalidProperties[] = "'partner' can't be null";
        }
        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets print_href
     *
     * @return string
     */
    public function getPrintHref()
    {
        return $this->container['print_href'];
    }

    /**
     * Sets print_href
     *
     * @param string $print_href print_href
     *
     * @return $this
     */
    public function setPrintHref($print_href)
    {
        $this->container['print_href'] = $print_href;

        return $this;
    }

    /**
     * Gets consignee_id
     *
     * @return int
     */
    public function getConsigneeId()
    {
        return $this->container['consignee_id'];
    }

    /**
     * Sets consignee_id
     *
     * @param int $consignee_id consignee_id
     *
     * @return $this
     */
    public function setConsigneeId($consignee_id)
    {
        $this->container['consignee_id'] = $consignee_id;

        return $this;
    }

    /**
     * Gets amount_untaxed
     *
     * @return float
     */
    public function getAmountUntaxed()
    {
        return $this->container['amount_untaxed'];
    }

    /**
     * Sets amount_untaxed
     *
     * @param float $amount_untaxed amount_untaxed
     *
     * @return $this
     */
    public function setAmountUntaxed($amount_untaxed)
    {
        $this->container['amount_untaxed'] = $amount_untaxed;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets partner_shipping_id
     *
     * @return int
     */
    public function getPartnerShippingId()
    {
        return $this->container['partner_shipping_id'];
    }

    /**
     * Sets partner_shipping_id
     *
     * @param int $partner_shipping_id partner_shipping_id
     *
     * @return $this
     */
    public function setPartnerShippingId($partner_shipping_id)
    {
        $this->container['partner_shipping_id'] = $partner_shipping_id;

        return $this;
    }

    /**
     * Gets order_line
     *
     * @return \Carooline\Model\OrderLine[]
     */
    public function getOrderLine()
    {
        return $this->container['order_line'];
    }

    /**
     * Sets order_line
     *
     * @param \Carooline\Model\OrderLine[] $order_line order_line
     *
     * @return $this
     */
    public function setOrderLine($order_line)
    {
        $this->container['order_line'] = $order_line;

        return $this;
    }

    /**
     * Gets mobile
     *
     * @return string
     */
    public function getMobile()
    {
        return $this->container['mobile'];
    }

    /**
     * Sets mobile
     *
     * @param string $mobile mobile
     *
     * @return $this
     */
    public function setMobile($mobile)
    {
        $this->container['mobile'] = $mobile;

        return $this;
    }

    /**
     * Gets amount_tax
     *
     * @return float
     */
    public function getAmountTax()
    {
        return $this->container['amount_tax'];
    }

    /**
     * Sets amount_tax
     *
     * @param float $amount_tax amount_tax
     *
     * @return $this
     */
    public function setAmountTax($amount_tax)
    {
        $this->container['amount_tax'] = $amount_tax;

        return $this;
    }

    /**
     * Gets invoice_ids
     *
     * @return \Carooline\Model\OrderInvoiceIds[]
     */
    public function getInvoiceIds()
    {
        return $this->container['invoice_ids'];
    }

    /**
     * Sets invoice_ids
     *
     * @param \Carooline\Model\OrderInvoiceIds[] $invoice_ids invoice_ids
     *
     * @return $this
     */
    public function setInvoiceIds($invoice_ids)
    {
        $this->container['invoice_ids'] = $invoice_ids;

        return $this;
    }

    /**
     * Gets state
     *
     * @return string
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     *
     * @param string $state state
     *
     * @return $this
     */
    public function setState($state)
    {
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets carrier
     *
     * @return \Carooline\Model\OrderCarrier
     */
    public function getCarrier()
    {
        return $this->container['carrier'];
    }

    /**
     * Sets carrier
     *
     * @param \Carooline\Model\OrderCarrier $carrier carrier
     *
     * @return $this
     */
    public function setCarrier($carrier)
    {
        $this->container['carrier'] = $carrier;

        return $this;
    }

    /**
     * Gets payment_transaction
     *
     * @return \Carooline\Model\OrderPaymentTransaction
     */
    public function getPaymentTransaction()
    {
        return $this->container['payment_transaction'];
    }

    /**
     * Sets payment_transaction
     *
     * @param \Carooline\Model\OrderPaymentTransaction $payment_transaction payment_transaction
     *
     * @return $this
     */
    public function setPaymentTransaction($payment_transaction)
    {
        $this->container['payment_transaction'] = $payment_transaction;

        return $this;
    }

    /**
     * Gets client_order_ref
     *
     * @return string
     */
    public function getClientOrderRef()
    {
        return $this->container['client_order_ref'];
    }

    /**
     * Sets client_order_ref
     *
     * @param string $client_order_ref client_order_ref
     *
     * @return $this
     */
    public function setClientOrderRef($client_order_ref)
    {
        $this->container['client_order_ref'] = $client_order_ref;

        return $this;
    }

    /**
     * Gets partner_invoice_id
     *
     * @return int
     */
    public function getPartnerInvoiceId()
    {
        return $this->container['partner_invoice_id'];
    }

    /**
     * Sets partner_invoice_id
     *
     * @param int $partner_invoice_id partner_invoice_id
     *
     * @return $this
     */
    public function setPartnerInvoiceId($partner_invoice_id)
    {
        $this->container['partner_invoice_id'] = $partner_invoice_id;

        return $this;
    }

    /**
     * Gets partner
     *
     * @return \Carooline\Model\Partner
     */
    public function getPartner()
    {
        return $this->container['partner'];
    }

    /**
     * Sets partner
     *
     * @param \Carooline\Model\Partner $partner partner
     *
     * @return $this
     */
    public function setPartner($partner)
    {
        $this->container['partner'] = $partner;

        return $this;
    }

    /**
     * Gets date_order
     *
     * @return string
     */
    public function getDateOrder()
    {
        return $this->container['date_order'];
    }

    /**
     * Sets date_order
     *
     * @param string $date_order date_order
     *
     * @return $this
     */
    public function setDateOrder($date_order)
    {
        $this->container['date_order'] = $date_order;

        return $this;
    }

    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets amount_total
     *
     * @return float
     */
    public function getAmountTotal()
    {
        return $this->container['amount_total'];
    }

    /**
     * Sets amount_total
     *
     * @param float $amount_total amount_total
     *
     * @return $this
     */
    public function setAmountTotal($amount_total)
    {
        $this->container['amount_total'] = $amount_total;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
