<?php
/**
 * PaymentTransactionSearchResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Carooline
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * sale REST services
 *
 * Get or Update Sales
 *
 * OpenAPI spec version: 0.1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.13
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Carooline;

/**
 * PaymentTransactionSearchResponseTest Class Doc Comment
 *
 * @category    Class
 * @description PaymentTransactionSearchResponse
 * @package     Carooline
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PaymentTransactionSearchResponseTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass() : void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp() : void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown() : void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass() : void
    {
    }

    /**
     * Test "PaymentTransactionSearchResponse"
     */
    public function testPaymentTransactionSearchResponse()
    {
    }

    /**
     * Test attribute "count"
     */
    public function testPropertyCount()
    {
    }

    /**
     * Test attribute "rows"
     */
    public function testPropertyRows()
    {
    }
}
