<?php
/**
 * PaymentTransactionUpdateRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Carooline
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * sale REST services
 *
 * Get or Update Sales
 *
 * OpenAPI spec version: 0.1.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.13
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Carooline;

/**
 * PaymentTransactionUpdateRequestTest Class Doc Comment
 *
 * @category    Class
 * @description PaymentTransactionUpdateRequest
 * @package     Carooline
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PaymentTransactionUpdateRequestTest extends \PHPUnit\Framework\TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass() : void
    {
    }

    /**
     * Setup before running each test case
     */
    protected function setUp() : void
    {
    }

    /**
     * Clean up after running each test case
     */
    protected function tearDown() : void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass() : void
    {
    }

    /**
     * Test "PaymentTransactionUpdateRequest"
     */
    public function testPaymentTransactionUpdateRequest()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "acquirer_reference"
     */
    public function testPropertyAcquirerReference()
    {
    }

    /**
     * Test attribute "reference"
     */
    public function testPropertyReference()
    {
    }

    /**
     * Test attribute "state_message"
     */
    public function testPropertyStateMessage()
    {
    }

    /**
     * Test attribute "date_validate"
     */
    public function testPropertyDateValidate()
    {
    }

    /**
     * Test attribute "partner_id"
     */
    public function testPropertyPartnerId()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "acquirer"
     */
    public function testPropertyAcquirer()
    {
    }
}
